[project]
name = "hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-data-tables>=12.7.0",
    "mysql-connector-python>=9.3.0",
    "paramiko>=3.5.1",
    "prefect>=3.4.2",
]
